services:
  app:
    build:
      context: .
      dockerfile: Enviroment/Dockerfiles/Dockerfile.app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
  db:
    build:
      context: .
      dockerfile: Enviroment/Dockerfiles/Dockerfile.db
    environment: 
      MYSQL_ROOT_PASSWORD: KOBIL123!
      MYSQL_DATABASE: fingerprint
    restart: always
    ports:
      - "3306:3306"