version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/fingerprintDB
      - ML_SERVER_URL=http://ml_server:5000
    depends_on:
      - db
      - ml_server
    restart: unless-stopped

  ml_server:
    build:
      context: .
      dockerfile: Dockerfile.ml
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URI=mongodb://db:27017/fingerprintDB
      - PYTHONPATH=/usr/src/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
