# Use NVIDIA CUDA image with CUDA 11.8 and CuDNN 8.6.0 development variant
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

# Set environment variable to disable interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Set CUDA_VISIBLE_DEVICES environment variable
ENV CUDA_VISIBLE_DEVICES=1

# Install basic dependencies and NVIDIA tools
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    wget \
    graphviz \
    nvidia-utils-460 \
    && rm -rf /var/lib/apt/lists/*

# Set working directory in the container
WORKDIR /app

# Copy requirements.txt to working directory
COPY requirements.txt .

# Install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the rest of the code to working directory
COPY . .

# Expose port 8888 for Jupyter Notebook
EXPOSE 8888

# Set command to run when container starts
CMD ["python3", "-m", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]