# Verwende ein NVIDIA CUDA Image mit CUDA 11.8 und CuDNN 8.6.0 in der Entwickler-Variante
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

# Setze die Umgebungsvariable, um interaktive Eingaben zu deaktivieren
ENV DEBIAN_FRONTEND=noninteractive

# Setze die CUDA_VISIBLE_DEVICES Umgebungsvariable
ENV CUDA_VISIBLE_DEVICES=1

# Installiere grundlegende Abhängigkeiten und NVIDIA-Tools
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    wget \
    graphviz \
    nvidia-utils-460 \
    && rm -rf /var/lib/apt/lists/*

# Setze das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere die requirements.txt in das Arbeitsverzeichnis
COPY requirements.txt .

# Installiere die Python-Abhängigkeiten
RUN pip3 install --no-cache-dir -r requirements.txt

# Kopiere den Rest des Codes in das Arbeitsverzeichnis
COPY . .

# Öffne den Port 8888 für Jupyter Notebook
EXPOSE 8888

# Setze den Befehl, der ausgeführt wird, wenn der Container startet
CMD ["python3", "-m", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]