FROM mysql:latest

# Setzen Sie die Umgebungsvariablen für MySQL
ENV MYSQL_ROOT_PASSWORD=KOBIL123!
ENV MYSQL_DATABASE=fingerprint

# Kopieren Sie die init.sql-Datei in das Docker-Image
COPY Database/init.sql /docker-entrypoint-initdb.d/

# Expose port 3306
EXPOSE 3306